import newhost
import hypercube
import prtcube
import hpmatrix
import lstdst
import neweffectorlist
import newpathogenunita
import scoresinit
import hilla
import hillb
import calcwij
import genomeinit
